PostSystem.Website/ViewModels/PostOfficeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace PostSystem.Website.ViewModels
{
    public class PostOfficeViewModel : BaseViewModel
    {
        [Required(ErrorMessage = "Моля въведете град")]
        [DisplayName("Град")]
        public int City_Id { get; set; }
        [Required(ErrorMessage = "Моля въведете код")]
        [Range(1000, 9999, ErrorMessage = "Невалиден пощенски код")]
        [DisplayName("Код на пощенски офис")]
        public int Office_Post_Code { get; set; }
        [StringLength(250, ErrorMessage = "{0}ът трябва да е по-кратък от {1} символа. ")]
        [Required(ErrorMessage = "Моля въведете адрес")]
        [DisplayName("Адрес")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Моля въведете брой гишета")]
        [DisplayName("Брой гишета")]
        public short Desk_Count { get; set; }
        public CityViewModel Office_City { get; set; }
    }
}

PostSystem.Website/Controllers/PostOfficesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using PostSystem.Website.ViewModels;

namespace PostSystem.Website.Controllers
{
    public class PostOfficesController : BaseController<PostOfficeViewModel>
    {
        private async Task<IEnumerable<SelectListItem>> GetCities()
        {
            using(var httpClient = new HttpClient())
            {
                var token = await GetAccessToken();
                if (token == null)Enumerable.Empty<SelectListItem>();
                    RedirectToAction(nameof(HomeController.Error), "Home");
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                HttpResponseMessage citiesResponse = await httpClient.GetAsync(WebsiteHelper.citiesUri);
                if (!citiesResponse.IsSuccessStatusCode)
                {
                    return Enumerable.Empty<SelectListItem>();
                }
                string citiesJsonResponse = await citiesResponse.Content.ReadAsStringAsync();
                var cities = JsonConvert.DeserializeObject<IEnumerable<CityViewModel>>(citiesJsonResponse);
                return cities.Select(city => new SelectListItem(city.City_Name, city.Id.ToString()));
            }
        }

        [HttpGet, ActionName("Index")]
        public async Task<ActionResult> GetAll([FromQuery] int city)
        {
            using (var client = new HttpClient())
            {
                var token = await GetAccessToken();
                if (token == null)
                    return RedirectToAction(nameof(HomeController.Error), "Home");
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                HttpResponseMessage response = await client.GetAsync($"{Uri}?city={city}");

                if (!response.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(HomeController.Error), "Home");
                }

                string jsonResponse = await response.Content.ReadAsStringAsync();

                var responseData = JsonConvert.DeserializeObject<IEnumerable<PostOfficeViewModel>>(jsonResponse);

                ViewBag.Cities = await GetCities();
                return View(responseData);
            }
        }

        public override async Task<ActionResult> Create()
        {
            ViewBag.Cities = await GetCities();

            return View();
        }

        public override async Task<ActionResult> Edit(int id)
        {
            using (var client = new HttpClient())
            {
                var token = await GetAccessToken();
                if (token == null)
                    return RedirectToAction(nameof(HomeController.Error), "Home");
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                HttpResponseMessage response = await client.GetAsync($"{Uri}/{id}");

                if (!response.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(HomeController.Error), "Home");
                }

                string jsonResponse = await response.Content.ReadAsStringAsync();

                var responseData = JsonConvert.DeserializeObject<PostOfficeViewModel>(jsonResponse);
                var cities = await GetCities();

                ViewBag.Cities = cities;
                
                return View(responseData);
            }
        }

        public PostOfficesController() : base(WebsiteHelper.postOfficesUri) {}
    }
}

PostSystem.Website/Views/PostOffices/Create.cshtml
@model PostSystem.Website.ViewModels.PostOfficeViewModel

@{
    ViewData["Title"] = "Нов пощенски офис";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Нов пощенски офис</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="City_Id" class="control-label"></label>
                @Html.DropDownListFor(office => office.City_Id, ViewBag.Cities as IEnumerable<SelectListItem>, htmlAttributes: new { @class = "form-control"})
                <span asp-validation-for="City_Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Office_Post_Code" class="control-label"></label>
                <input asp-for="Office_Post_Code" class="form-control" />
                <span asp-validation-for="Office_Post_Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Desk_Count" class="control-label"></label>
                <input asp-for="Desk_Count" class="form-control" />
                <span asp-validation-for="Desk_Count" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.HiddenFor(office => office.Id)
            </div>
            <div class="form-group">
                @Html.HiddenFor(office => office.Created_On)
            </div>
            <div class="form-group">
                @Html.HiddenFor(office => office.Updated_On)
            </div>
            <div class="form-group">
                <input type="submit" value="Създай" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Обратно</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PostSystem.Website/Views/PostOffices/Delete.cshtml
@model PostSystem.Website.ViewModels.PostOfficeViewModel

@{
    ViewData["Title"] = "Изтриване на пощенски офис";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Потвърдете изтриване на пощенски офис</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City_Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City_Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Office_Post_Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Office_Post_Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Desk_Count)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Desk_Count)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created_On)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created_On)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Updated_On)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Updated_On)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Изтрий" class="btn btn-danger" /> |
        <a asp-action="Index">Обратно</a>
    </form>
</div>

PostSystem.Website/Views/PostOffices/Details.cshtml
@model PostSystem.Website.ViewModels.PostOfficeViewModel

@{
    ViewData["Title"] = "Подробности за пощенски офис";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Подробности</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City_Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Office_City.City_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Office_Post_Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Office_Post_Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Desk_Count)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Desk_Count)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created_On)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created_On)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Updated_On)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Updated_On)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.Id }) |
    <a asp-action="Index">Обратно</a>
</div>

PostSystem.Website/Views/PostOffices/Edit.cshtml
@model PostSystem.Website.ViewModels.PostOfficeViewModel

@{
    ViewData["Title"] = "Редактиране на пощенски офис";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="City_Id" class="control-label"></label>
                @Html.DropDownListFor(office => office.City_Id, ViewBag.Cities as IEnumerable<SelectListItem>, new { @class = "form-control" })
                <span asp-validation-for="City_Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Office_Post_Code" class="control-label"></label>
                <input asp-for="Office_Post_Code" class="form-control" />
                <span asp-validation-for="Office_Post_Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Desk_Count" class="control-label"></label>
                <input asp-for="Desk_Count" class="form-control" />
                <span asp-validation-for="Desk_Count" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" hidden/>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Created_On" class="control-label"></label>
                <input asp-for="Created_On" class="form-control" hidden/>
                <span asp-validation-for="Created_On" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Updated_On" class="control-label"></label>
                <input asp-for="Updated_On" class="form-control" hidden/>
                <span asp-validation-for="Updated_On" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Запази" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Обратно</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PostSystem.Website/Views/PostOffices/Index.cshtml
@model IEnumerable<PostSystem.Website.ViewModels.PostOfficeViewModel>

@{
    ViewData["Title"] = "Пощенски офиси";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Пощенски офиси</h1>

<p>
    <a asp-action="Create">Нов пощенски офис</a>
</p>

@using (Html.BeginForm("Index", "PostOffices", FormMethod.Get))
{
    @Html.Label("Град: ")
    @Html.DropDownList("city", ViewBag.Cities as IEnumerable<SelectListItem>, htmlAttributes: new { @class = "form-control" })
    <input type="submit" value="Търсене" />
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.City_Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Office_Post_Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Office_City.City_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Office_Post_Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.ActionLink("Редактирай", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Подробности", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Изтрий", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>