PostSystem.Website/ViewModels/DeliveryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace PostSystem.Website.ViewModels
{
    public class DeliveryViewModel : BaseViewModel
    {
        [Required(ErrorMessage = "Моля въведете описание на колет")]
        [DisplayName("Колет")]
        public int Mail_Id { get; set; }
        [Required(ErrorMessage = "Моля въведете пощенски офис")]
        [DisplayName("От пощенски офис")]
        public int From_Office_Id { get; set; }
        [Required(ErrorMessage = "Моля въведете пощенски офис")]
        [DisplayName("Към пощенски офис")]
        public int To_Office_Id { get; set; }
        [StringLength(250, ErrorMessage = "Полето за описанието трябва да е по-кратко от {1} символа. ")]
        [DisplayName("Описание")]
        public string Details { get; set; }
        [DisplayName("Такса")]
        public double Tax { get; set; }
        [DisplayName("Експресна услуга")]
        public bool Express_Delivery { get; set; }
        public MailViewModel Delivery_Mail { get; set; }
        public PostOfficeViewModel From_Delivery_Office { get; set; }
        public PostOfficeViewModel To_Delivery_Office { get; set; }
    }
}

PostSystem.Website/Controllers/DeliveriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using PostSystem.Website.ViewModels;

namespace PostSystem.Website.Controllers
{
    public class DeliveriesController : BaseController<DeliveryViewModel>
    {
        private async Task<IEnumerable<MailViewModel>> GetAllMails(HttpClient httpClient)
        {

            var token = await GetAccessToken();
            if (token == null)
                return Enumerable.Empty<MailViewModel>();
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            
            HttpResponseMessage mailsResponse = await httpClient.GetAsync(WebsiteHelper.mailsUri);
            
            if (!mailsResponse.IsSuccessStatusCode)
            {
                return Enumerable.Empty<MailViewModel>();
            }
            string mailsJsonResponse = await mailsResponse.Content.ReadAsStringAsync();
            var mails = JsonConvert.DeserializeObject<IEnumerable<MailViewModel>>(mailsJsonResponse);
            return mails;
        }

        private async Task<IEnumerable<DeliveryViewModel>> GetAllDeliveries(HttpClient httpClient)
        {
            var token = await GetAccessToken();
            if (token == null)
                return Enumerable.Empty<DeliveryViewModel>();
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            HttpResponseMessage deliveriesResponse = await httpClient.GetAsync(WebsiteHelper.deliveriesUri);

            if (!deliveriesResponse.IsSuccessStatusCode)
            {
                return Enumerable.Empty<DeliveryViewModel>();
            }
            string deliveriesJsonResponse = await deliveriesResponse.Content.ReadAsStringAsync();
            var deliveries = JsonConvert.DeserializeObject<IEnumerable<DeliveryViewModel>>(deliveriesJsonResponse);
            return deliveries;
        }


        private async Task<IEnumerable<SelectListItem>> GetMails(int currentMailItem = 0)
        {

            using (var httpClient = new HttpClient())
            {
                var token = await GetAccessToken();
                if (token == null)
                    return Enumerable.Empty<SelectListItem>();
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                var mails = await GetAllMails(httpClient);
                var deliveries = await GetAllDeliveries(httpClient);

                List<MailViewModel> remainingMails = new List<MailViewModel>();

                foreach(var mail in mails)
                {
                    bool inUse = false;
                    foreach (var delivery in deliveries)
                    {
                        if (mail.Id != currentMailItem && mail.Id == delivery.Delivery_Mail.Id)
                            inUse = true;
                    }
                    if (!inUse)
                        remainingMails.Add(mail);
                }
                mails = remainingMails;

                return mails.Select(mail => new SelectListItem($"#{mail.Id} - {mail.Description}", mail.Id.ToString()));
            }
        }

        private async Task<IEnumerable<SelectListItem>> GetOffices()
        {
            using (var httpClient = new HttpClient())
            {
                var token = await GetAccessToken();
                if (token == null)
                    return Enumerable.Empty<SelectListItem>();
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                HttpResponseMessage officesResponse = await httpClient.GetAsync(WebsiteHelper.postOfficesUri);
                if (!officesResponse.IsSuccessStatusCode)
                {
                    return Enumerable.Empty<SelectListItem>();
                }
                string officesJsonResponse = await officesResponse.Content.ReadAsStringAsync();
                var offices = JsonConvert.DeserializeObject<IEnumerable<PostOfficeViewModel>>(officesJsonResponse);
                return offices.Select(office => new SelectListItem($"{office.Office_City.City_Name} {office.Office_Post_Code}, {office.Address}", office.Id.ToString()));
            }
        }

        [HttpGet, ActionName("Index")]
        public async Task<ActionResult> GetAll([FromQuery] int officeCode)
        {
            using (var client = new HttpClient())
            {
                var token = await GetAccessToken();
                if (token == null)
                    return RedirectToAction(nameof(HomeController.Error), "Home");
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                HttpResponseMessage response = await client.GetAsync($"{Uri}?officeCode={officeCode}");

                if (!response.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(HomeController.Error), "Home");
                }

                string jsonResponse = await response.Content.ReadAsStringAsync();

                var responseData = JsonConvert.DeserializeObject<IEnumerable<DeliveryViewModel>>(jsonResponse);

                return View(responseData);
            }
        }


        public override async Task<ActionResult> Create()
        {
            ViewBag.Mails = await GetMails();
            ViewBag.PostOffices = await GetOffices();

            return View();
        }

        public override async Task<ActionResult> Edit(int id)
        {
            using (var client = new HttpClient())
            {
                var token = await GetAccessToken();
                if (token == null)
                    return RedirectToAction(nameof(HomeController.Error), "Home");
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                HttpResponseMessage response = await client.GetAsync($"{Uri}/{id}");

                if (!response.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(HomeController.Error), "Home");
                }

                string jsonResponse = await response.Content.ReadAsStringAsync();

                var responseData = JsonConvert.DeserializeObject<DeliveryViewModel>(jsonResponse);
                var deliveries = await GetAllDeliveries(client);
                DeliveryViewModel model = deliveries.Where(del => del.Id == id).FirstOrDefault();

                ViewBag.Mails = await GetMails(model.Delivery_Mail.Id);
                ViewBag.PostOffices = await GetOffices();

                return View(responseData);
            }
        }

        public DeliveriesController() : base(WebsiteHelper.deliveriesUri) { }
    }
}

PostSystem.Website/Views/Deliveries/Create.cshtml
@model PostSystem.Website.ViewModels.DeliveryViewModel

@{
    ViewData["Title"] = "Нова пратка";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Нова пратка</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Mail_Id" class="control-label"></label>
                @Html.DropDownListFor(delivery => delivery.Mail_Id, ViewBag.Mails as IEnumerable<SelectListItem>, htmlAttributes: new { @class = "form-control" })
                <span asp-validation-for="Mail_Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="From_Office_Id" class="control-label"></label>
                @Html.DropDownListFor(delivery => delivery.From_Office_Id, ViewBag.PostOffices as IEnumerable<SelectListItem>, htmlAttributes: new { @class = "form-control" })
                <span asp-validation-for="From_Office_Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="To_Office_Id" class="control-label"></label>
                @Html.DropDownListFor(delivery => delivery.To_Office_Id, ViewBag.PostOffices as IEnumerable<SelectListItem>, htmlAttributes: new { @class = "form-control" })
                <span asp-validation-for="To_Office_Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Details" class="control-label"></label>
                <input asp-for="Details" class="form-control" />
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tax" class="control-label"></label> <label class="control-label">(в лв.)</label>
                <input asp-for="Tax" class="form-control" />
                <span asp-validation-for="Tax" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Express_Delivery" /> @Html.DisplayNameFor(model => model.Express_Delivery)
                </label>
            </div>
            <div class="form-group">
                @Html.HiddenFor(model => model.Id)
            </div>
            <div class="form-group">
                @Html.HiddenFor(model => model.Created_On)
            </div>
            <div class="form-group">
                @Html.HiddenFor(model => model.Updated_On)
            </div>
            <div class="form-group">
                <input type="submit" value="Създай" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Обратно</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PostSystem.Website/Views/Deliveries/Delete.cshtml
@model PostSystem.Website.ViewModels.DeliveryViewModel

@{
    ViewData["Title"] = "Изтриване на пратка";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Потвърдете изтриване на пратка</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mail_Id)
        </dt>
        <dd class="col-sm-10">
            #@Html.DisplayFor(model => model.Delivery_Mail.Id) - @Html.DisplayFor(model => model.Delivery_Mail.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.From_Office_Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.From_Delivery_Office.Office_City.City_Name) @Html.DisplayFor(model => model.From_Delivery_Office.Office_Post_Code), @Html.DisplayFor(model => model.From_Delivery_Office.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.To_Office_Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.To_Delivery_Office.Office_City.City_Name) @Html.DisplayFor(model => model.To_Delivery_Office.Office_Post_Code), @Html.DisplayFor(model => model.To_Delivery_Office.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tax)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tax) лв.
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Express_Delivery)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Express_Delivery)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created_On)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created_On)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Updated_On)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Updated_On)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Изтрий" class="btn btn-danger" /> |
        <a asp-action="Index">Обратно</a>
    </form>
</div>

PostSystem.Website/Views/Deliveries/Details.cshtml
@model PostSystem.Website.ViewModels.DeliveryViewModel

@{
    ViewData["Title"] = "Подробности за пратка";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Подробности</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Mail_Id)
        </dt>
        <dd class="col-sm-10">
            #@Html.DisplayFor(model => model.Delivery_Mail.Id) - @Html.DisplayFor(model => model.Delivery_Mail.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.From_Office_Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.From_Delivery_Office.Office_City.City_Name) @Html.DisplayFor(model => model.From_Delivery_Office.Office_Post_Code), @Html.DisplayFor(model => model.From_Delivery_Office.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.To_Office_Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.To_Delivery_Office.Office_City.City_Name) @Html.DisplayFor(model => model.To_Delivery_Office.Office_Post_Code), @Html.DisplayFor(model => model.To_Delivery_Office.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tax)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tax) лв.
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Express_Delivery)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Express_Delivery)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Created_On)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Created_On)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Updated_On)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Updated_On)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Редактирай", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Обратно</a>
</div>

PostSystem.Website/Views/Deliveries/Edit.cshtml
@model PostSystem.Website.ViewModels.DeliveryViewModel

@{
    ViewData["Title"] = "Редактиране на пратка";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Mail_Id" class="control-label"></label>
                @Html.DropDownListFor(delivery => delivery.Mail_Id, ViewBag.Mails as IEnumerable<SelectListItem>, htmlAttributes: new { @class = "form-control" })
                <span asp-validation-for="Mail_Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="From_Office_Id" class="control-label"></label>
                @Html.DropDownListFor(delivery => delivery.From_Office_Id, ViewBag.PostOffices as IEnumerable<SelectListItem>, htmlAttributes: new { @class = "form-control" })
                <span asp-validation-for="From_Office_Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="To_Office_Id" class="control-label"></label>
                @Html.DropDownListFor(delivery => delivery.To_Office_Id, ViewBag.PostOffices as IEnumerable<SelectListItem>, htmlAttributes: new { @class = "form-control" })
                <span asp-validation-for="To_Office_Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Details" class="control-label"></label>
                <input asp-for="Details" class="form-control" />
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tax" class="control-label"></label> <label class="control-label">(в лв.)</label>
                <input asp-for="Tax" class="form-control" />
                <span asp-validation-for="Tax" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Express_Delivery" /> @Html.DisplayNameFor(model => model.Express_Delivery)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Id" class="control-label" hidden></label>
                <input asp-for="Id" class="form-control" hidden/>
                <span asp-validation-for="Id" class="text-danger" hidden></span>
            </div>
            <div class="form-group">
                <label asp-for="Created_On" class="control-label" hidden></label>
                <input asp-for="Created_On" class="form-control" hidden/>
                <span asp-validation-for="Created_On" class="text-danger" hidden></span>
            </div>
            <div class="form-group">
                <label asp-for="Updated_On" class="control-label" hidden></label>
                <input asp-for="Updated_On" class="form-control" hidden/>
                <span asp-validation-for="Updated_On" class="text-danger" hidden></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Запази" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Обратно</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PostSystem.Website/Views/Deliveries/Index.cshtml
@model IEnumerable<PostSystem.Website.ViewModels.DeliveryViewModel>

@{
    ViewData["Title"] = "Пратки";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Пратки</h1>

<p>
    <a asp-action="Create">Нова пратка</a>
</p>

@using (Html.BeginForm("Index", "Deliveries", FormMethod.Get))
{
    @Html.Label("Пощенски код: ")
    <input id="officeCode" name="officeCode" />
    <input type="submit" value="Търсене" />
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Mail_Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.From_Office_Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.To_Office_Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Details)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    #@Html.DisplayFor(modelItem => item.Delivery_Mail.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.From_Delivery_Office.Office_City.City_Name), @Html.DisplayFor(modelItem => item.From_Delivery_Office.Office_Post_Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.To_Delivery_Office.Office_City.City_Name), @Html.DisplayFor(modelItem => item.To_Delivery_Office.Office_Post_Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Details)
                </td>
                <td>
                    @Html.ActionLink("Редактирай", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Подробности", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Изтрий", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>